version: '3.8'

services:
  # Strapi Application (with Supabase + Cloudinary)
  strapi:
    container_name: barbitch-strapi
    build:
      context: .
      dockerfile: Dockerfile
    image: barbitch-strapi:latest
    restart: unless-stopped
    env_file: .env
    environment:
      NODE_ENV: production
      HOST: 0.0.0.0
      PORT: 1350
    ports:
      - '1350:1350'
    networks:
      - strapi-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:1350/_health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

networks:
  strapi-network:
    driver: bridge
